### ISSUE TITLE
Considerations for GLMM?

### ISSUE THREAD

**Issue by seanhardison1** [murphymv/semEff#17]
Hi Mark,

Great package! I'm interested to know how `semEff` handles estimating standardized coefficients for GLMMs, if at all. Should users set `use.raw = T` with GLMMs? How are direct/indirect effects handled in this case?

Thanks

Sean

**Comment by murphymv** [comment]
Hi Sean,

For GLM(M)s with non-gaussian error distributions, fully standardised effects (coefficients) are achieved by dividing by the standard deviation of the link-transformed response variable, or where this produces undefined values, of an empirical estimate of this variable. This estimate is obtained via iterative fitting of a GLM to the response variable — see `?semEff::glt()` for details. It is somewhat of a hack, but always produces a variable who's inverse-transformation is very close to the original response, and so it's 'reasonableness' is assessed that way. The advantage of estimating a variable instead of just it's variance (like previous solutions do), is that this variable can then be fitted to downstream responses in order to calculate indirect effects correctly (i.e. using the same scale), which I don't think was previously possible. In this scenario, you would use `glt()` to transform a copy of the variable in your dataset to use as a predictor in other models.

It is not a perfect solution by any means, but then this is a hard problem, so it's a case of picking the least worst option in my view (i.e. all solutions are wrong; some are useful). This solution at least is generalisable to any model which uses a link function (within supported model classes of course), seems to closely resemble OLS standardised coefficients, and allows 'proper' indirect effects. I came up with this as I was not happy with previous solutions, but always open to feedback (particularly as it is not published... at least yet).

The `use.raw` argument of `semEff()` is designed to calculate effects using completely unstandardised coefficients (in case that is desired for whatever reason), and will extract those from the ouput of `stdEff(..., incl.raw = TRUE)`. You can also choose to exclude response-standardisation (`std.y = FALSE`), and there are a few more options in there for flexibility.

Incidentally I have a new version of this package upcoming with new print and summary methods and some other improvements, so hopefully out soon (can install dev branch to try out in meantime).

Cheers,
Mark
