### ISSUE TITLE
semEff documentation not clear for using psem objects

### ISSUE THREAD

**Issue by Canderson156** [murphymv/semEff#40]
The documentation for semEff suggests that for sem, one can provide either a list or a psem object. It appears that this is the only object that would need to be provided. 

keeley.psem <- psem(
  lm(age ~ distance, data = keeley),
  lm(hetero ~ distance, data = keeley),
  lm(abiotic ~ distance, data = keeley),
  lm(firesev ~ age, data = keeley),
  lm(cover ~ firesev, data = keeley),
  lm(rich ~ distance + hetero + abiotic + cover, data = keeley)
)

> x <- semEff(keeley.psem)
Error in bootEff(sem, ...) : 
  Number of bootstrap resamples (R) must be specified.

I deduced from this error message that if a psem object is provided, bootEff must be run within the function. It would be helpful to indicate this in the documentation, and that additional arguments are required when sem is a psem object.

**Comment by murphymv** [comment]
Hi Christine,

From `?semEff()`, last line of first paragraph under Details:

> If sem is a list of fitted models, effects will first be bootstrapped using bootEff() (this may take a while!).

Bootstrapping is used to generate CIs for all the effects, so `bootEff()` must be run first if it hasn't been already. I used to set a default value for `R` so that the function would just run without specifying any arguments, but I thought it would be more useful/sensible to be explicit and force the user to think about how many replicates they need for their context (and also so that they can more easily remember/report the number used). 

I could however also add an optional `R` argument to `semEff()`, to make it clearer that the number of replicates needs to be provided one way or the other. I'll have a think about it.

Thanks,
Mark
