### ISSUE TITLE
Documentation on standardization

### ISSUE THREAD

**Issue by alaindanet** [murphymv/semEff#41]
I do not find documentation of how exactly you standardize the effects in the SEM.

Do you refit the model with standardized variables, i.e. centering and scaling, or you standardize the coefficients after the model evaluation ? Could you also point me toward a reference for the adjustment for semi-partial correlation ?

**Comment by murphymv** [comment]
Hi Alain,

Standardisation is all explained in the documentation for [stdEff()](https://murphymv.github.io/semEff/reference/stdEff.html), with relevant references therein. But basically, the coefficients themselves are standardised rather than the variables (except in some limited cases where mean-centring of variables is also done, e.g. interactions).

Cheers,
Mark

**Comment by alaindanet** [comment]
Thank you so much, that is perfect.

May be it is useful to point toward the documentation of stdEff() in the doc in semEff(). Because, right now, we need to go from semEff() to bootEff() and from bootEff() to stdEff().

A proposition:
 ```r
#'   Direct effects are calculated as fully standardised model coefficients for
#'   each response variable (see [stdEff()] for details), while indirect effects are the product of these
#'   direct effects operating along causal pathways in the SEM. The total
```

**Comment by murphymv** [comment]
Thanks Alain, that's a good suggestion, I'll prob update that documentation in the next patch release, due soon.
