### ISSUE TITLE
How to use semEff with glmmTMB?

### ISSUE THREAD

**Issue by sinushelf** [murphymv/semEff#50]
Hi Mark,

I would like to calculate the direct and indirect effects of a `psem()` using glmmTMB() and lm().

I use this code:
keeley.sem <- list(
  glmmTMB(Variable1 ~  Variable2   + (1 | random), data = dat, family =gaussian(link = "identity")),
  glmmTMB(Variable2 ~ Variable3 +Variable4 + Variable5 + Variable6 + 
            Variable7+ (1 | random), data = dat, family =gaussian(link = "identity")),
  lm(Variable6  ~  Variable7+ Variable3, data = dat), 
  lm(Variable4  ~  Variable5+ Variable6 , data = dat)
)
keeley.sem.eff <- semEff(keeley.sem, R = 1000, seed = 13, ran.eff= "random")
summary(keeley.sem.eff)

I tried using bootEff() as in R's help page before using semEff(), but it didn't work as well.

I also got a warning message when I tried the code with lmer() instead of glmmTMB(): "Warning message:
In bootEff(sem, ...): Mixed and unmixed models together in one list. Resampling will treat all models as mixed." 

I have two questions:
- Does semEff() work for glmmTMB() or how can I handle it?
- Can I use mixed and non mixed models in one modellist and get reliable results?

Thanks a lot!
Sina

**Comment by murphymv** [comment]
Hi Sina,

Apologies for delayed response. Currently the package doesn't officially support glmmTMB models. The list of supported models is provided in the README. Supporting new model types is based on user demand and my time, but in some cases might not be too difficult. I don't currently have much time to do that though, so maybe you could use an alternative supported model type (e.g. `glmer`) in the meantime? Or you are always welcome to contribute code that provides support.

On the other question, yes you can use mixed and non-mixed models in the same SEM, if it makes sense to do so. The bootstrapping will however treat all models as mixed, as it will be assumed that the data is hieararchical and will resample based on the (highest-level) group (random effect). So it will resample groups instead of rows (that's if you use the default sampling type of 'nonparametric'). Is there a reason why you are not using mixed models for the `lm()` models? Usually you should do so if the data is hiearchical, unless the random effect variance is close to zero.

Cheers,
Mark
